close_ret:
  func_name: "ret"
  args:
    - "close"
  kwargs:
    shift: 1

pv_corr:
  func_name: "roll_spear_corr"
  args:
    - "close"
    - "vol"
  kwargs: {}

close_ret_5min:
  "ret(close, shift=5*60)"