SnapshotRaw:
    time_col: "tradetime"
    sec_col: "securityid"
    feat_cols:
        ask_size1: 'ask_size1'
        ask_size2: 'ask_size2'
        ask_size3: 'ask_size3'
        ask_size4: 'ask_size4'
        ask_size5: 'ask_size5'
        ask_size6: 'ask_size6'
        ask_size7: 'ask_size7'
        ask_size8: 'ask_size8'
        ask_size9: 'ask_size9'
        ask_size10: 'ask_size10'
        bid_size1: 'bid_size1'
        bid_size2: 'bid_size2'
        bid_size3: 'bid_size3'
        bid_size4: 'bid_size4'
        bid_size5: 'bid_size5'
        bid_size6: 'bid_size6'
        bid_size7: 'bid_size7'
        bid_size8: 'bid_size8'
        bid_size9: 'bid_size9'
        bid_size10: 'bid_size10'
        ask1: 'ask1'
        ask2: 'ask2'
        ask3: 'ask3'
        ask4: 'ask4'
        ask5: 'ask5'
        ask6: 'ask6'
        ask7: 'ask7'
        ask8: 'ask8'
        ask9: 'ask9'
        ask10: 'ask10'
        bid1: 'bid1'
        bid2: 'bid2'
        bid3: 'bid3'
        bid4: 'bid4'
        bid5: 'bid5'
        bid6: 'bid6'
        bid7: 'bid7'
        bid8: 'bid8'
        bid9: 'bid9'
        bid10: 'bid10'